In [3]:
import tensorflow as tf

# placeholder for input
x = tf.placeholder(dtype=tf.float32)

# define the computational graph
y = tf.pow((2*x),2)+(2*x)+1

# initialize the variables
init_op = tf.global_variables_initializer()

# create a session
sess = tf.Session()

sess.run(init_op)

# run the computational graph with input 10 to x
value = sess.run(y, feed_dict={x:10})

print(value)

421.0


In [9]:
# create random variable
weights = tf.Variable(tf.random_normal(shape=[10]))

sess.run(tf.global_variables_initializer())

sess.run(weights)

array([-2.4112203 ,  0.20118073, -0.73734826,  1.969944  ,  0.06586387,
        0.08083916,  0.07577373,  0.65543133, -1.3508545 ,  0.5003863 ],
      dtype=float32)

In [10]:
from sklearn.datasets import load_iris

x = load_iris().data
y = load_iris().target

x[:10], y[:10]

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1]]), array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [11]:
import numpy as np

np.unique(y)

array([0, 1, 2])

In [0]:
# batch size, 4
input_features = tf.placeholder(dtype=tf.float32, shape=[None, 4])

# batch size, 3
input_labels = tf.placeholder(dtype=tf.float32, shape=[None, 3])

# 4, 3
weights = tf.Variable(tf.random_normal(shape=[4,3]))
# 3
biases = tf.Variable(tf.random_normal(shape=[3]))

# [batch_size, 4] x [4,3]
linear_model = tf.add(tf.matmul(input_features, weights), biases)

# average (wx+b - y)**2
loss = tf.reduce_mean(tf.square(linear_model - input_labels))
train_op = tf.train.GradientDescentOptimizer(learning_rate=0.001).minimize(loss)

In [17]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())

def next_batch(batch_size, features, labels):
  indices = np.arange(start=0, stop=features.shape[0])
  np.random.shuffle(indices)
  indices = indices[:batch_size]
  return features[indices], labels[indices]

batch_size=16
for epoch in range(10):
  for index in range(int(x.shape[0]/batch_size)):
    mini_batch_x, mini_batch_y = next_batch(batch_size=batch_size, features=x, labels=y)
    
    from keras.utils import to_categorical
    mini_batch_y = to_categorical(mini_batch_y)
    _, train_loss = sess.run([train_op, loss], feed_dict={
        input_features: mini_batch_x,
        input_labels: mini_batch_y
    })
  print('Epoch {}, loss {}'.format(epoch, train_loss))

Using TensorFlow backend.


Epoch 0, loss 31.882591247558594
Epoch 1, loss 16.842405319213867
Epoch 2, loss 8.942944526672363
Epoch 3, loss 5.090244770050049
Epoch 4, loss 2.82244610786438
Epoch 5, loss 1.5684505701065063
Epoch 6, loss 1.2286795377731323
Epoch 7, loss 1.2352204322814941
Epoch 8, loss 0.8967239260673523
Epoch 9, loss 0.5441622734069824
